#page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1540174159 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
  # https://github.com/Aayush9029/PhoneML-Site/releases/download/v2.0/PhoneML.PressKit.zip # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Mordern To-Do List app, MacOS app, iPadOS and iOS app syncs with each other so you can always stay up-to-date with your tasks no matter which device you're using.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Aayush Pokharel
your_link: https://aayush.art
your_city: Toronto 🇨🇦
email_address: developer@aayush.art
facebook_username:
instagram_username:
twitter_username:
github_username: Aayush9029
youtube_username: NerdAware

#  Update the feature list given descriptions
# Feature List
features:
  - title: Get Organized
    description: You can organize  homeworks, upcoming quizzes or even activies like gaming, hanging out with friends so that you always know what tasks are pending and need your most attention. 
    fontawesome_icon_name: calendar

  - title: Widgets
    description: Custom hand crafted lets you see your tasks and joing online meeting links right from your Home Screen. Extra Large Widgets is available for the iPad running iPadOS 15 or later.
    fontawesome_icon_name: mobile

  - title: iCloud Sync
    description: IDL is available for iPad, iPhone and even MacOs devices, you can save your tasks and meetings from any device you have atm and it seamlessly sync between one another.
    fontawesome_icon_name: cloud


  - title: Dark Mode
    description: IDL supports dark mode, so you can use the app in dark mode and it will automatically switch between light and dark mode based on your system settings.
    fontawesome_icon_name: moon



# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.05
topbar_title_color: "#ffffff"

cover_image: assets/tasks.webp # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: blue # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
